"""Userspace model of socket-buffer occupancy and a fixed record ring.

Samples are packed into a bytearray indexed by a power-of-two mask. The ring
stays in this process. Kafka topic ``sec.sock.ring`` is the name a deployment
would publish; nothing here is copied onto a socket. The process does not open
network sockets and does not request CAP_NET_RAW. ``/proc/net/sockstat`` text
is generated by this program and parsed as text, never read from the host.
"""

from __future__ import annotations

import asyncio
import logging
import math
import statistics
import struct
import sys
from collections import deque

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    force=True,
)
LOGGER = logging.getLogger("sec.sock.inspector")


class EngineKernelException(Exception):
    """Raised when a sample or a ring slot fails validation."""


class SocketRingInspector:
    """Fixed bytearray ring of sk_buff-style occupancy records."""

    CAPACITY = 1024
    MASK = CAPACITY - 1
    INDEX_MASK = 0xFFFFFFFF
    NEAR_RATIO = 0.85
    STALL_WRITES = 32
    DROP_STREAK = 3
    PAGE_BYTES = 4096
    TOPIC = "sec.sock.ring"
    FRAME = struct.Struct("<HIIIIH")
    _FIELDS = ("queue_depth", "drops", "rmem_alloc", "wmem_alloc", "state")

    def __init__(self) -> None:
        exponent = math.log2(self.CAPACITY)
        if exponent != math.floor(exponent) or self.CAPACITY & (self.CAPACITY - 1):
            raise EngineKernelException("capacity must be a power of two")
        if self.FRAME.size != 20:
            raise EngineKernelException("occupancy record width drifted")
        self._lock = asyncio.Lock()
        self._ring = bytearray(self.CAPACITY * self.FRAME.size)
        self._head = 0
        self._tail = 0
        self._last_drops: int | None = None
        self._drop_rise = 0
        self._unconsumed_writes = 0
        self._warnings = 0
        self._latched = {
            "near": False,
            "drops": False,
            "stall": False,
            "full": False,
        }
        self._depths: deque[float] = deque(maxlen=64)

    async def observe(self, sample: dict[str, int]) -> dict[str, object]:
        """Pack one synthetic occupancy sample into the local ring."""
        await asyncio.sleep(0)
        async with self._lock:
            return self._observe_unlocked(sample)

    async def consume_one(self) -> dict[str, object]:
        """Read the oldest record. A damaged length field is a hard fault."""
        await asyncio.sleep(0)
        async with self._lock:
            return self._consume_unlocked()

    def prime_indices(self, head: int, tail: int) -> None:
        """Place the uint32 head and tail, including the overflow boundary."""
        head_i = self._mask_index(head, "head")
        tail_i = self._mask_index(tail, "tail")
        occupancy = (tail_i - head_i) & self.INDEX_MASK
        if occupancy > self.CAPACITY:
            raise EngineKernelException("primed occupancy exceeds capacity")
        self._head = head_i
        self._tail = tail_i
        self._unconsumed_writes = 0

    def overlay_length(self, index: int, length: int) -> None:
        """Install a length prefix so a damaged slot can be detected on read."""
        slot_index = self._mask_index(index, "index")
        if isinstance(length, bool) or not isinstance(length, int):
            raise EngineKernelException("length must be an int")
        if length < 0 or length > 0xFFFF:
            raise EngineKernelException("length exceeds record width")
        slot = slot_index & self.MASK
        struct.pack_into("<H", self._ring, slot * self.FRAME.size, length)

    def render_sockstat(self, used: int, tcp_mem: int, udp_mem: int) -> str:
        """Build synthetic sockstat text. This is not read from the host."""
        for label, value in (
            ("used", used),
            ("tcp_mem", tcp_mem),
            ("udp_mem", udp_mem),
        ):
            if isinstance(value, bool) or not isinstance(value, int) or value < 0:
                raise EngineKernelException(
                    f"sockstat {label} must be a non-negative int"
                )
        return (
            f"sockets: used {used}\n"
            f"TCP: inuse 40 orphan 0 tw 5 alloc 48 mem {tcp_mem}\n"
            f"UDP: inuse 8 mem {udp_mem}\n"
        )

    def parse_sockstat(self, text: str) -> dict[str, int]:
        """Parse sockstat-style text this process generated."""
        if not isinstance(text, str) or not text.strip():
            raise EngineKernelException("sockstat text is incomplete")
        used: int | None = None
        tcp_mem: int | None = None
        udp_mem: int | None = None
        for raw_line in text.splitlines():
            line = raw_line.strip()
            if not line:
                continue
            parts = line.split()
            try:
                if (
                    line.startswith("sockets:")
                    and len(parts) >= 3
                    and parts[1] == "used"
                ):
                    used = int(parts[2])
                elif line.startswith("TCP:") and "mem" in parts:
                    tcp_mem = int(parts[parts.index("mem") + 1])
                elif line.startswith("UDP:") and "mem" in parts:
                    udp_mem = int(parts[parts.index("mem") + 1])
            except (ValueError, IndexError) as exc:
                raise EngineKernelException("sockstat field is not an integer") from exc
        if used is None or tcp_mem is None or udp_mem is None:
            raise EngineKernelException("sockstat text is incomplete")
        return {"used": used, "tcp_mem": tcp_mem, "udp_mem": udp_mem}

    def _observe_unlocked(self, sample: dict[str, int]) -> dict[str, object]:
        depth, drops, rmem, wmem, state = self._coerce(sample)
        occupancy = (self._tail - self._head) & self.INDEX_MASK
        if occupancy >= self.CAPACITY:
            self._latch(
                "full",
                f"ring occupancy {occupancy}/{self.CAPACITY} at capacity",
            )
            raise EngineKernelException("ring at capacity")
        slot = self._tail & self.MASK
        offset = slot * self.FRAME.size
        self.FRAME.pack_into(
            self._ring,
            offset,
            self.FRAME.size,
            depth,
            drops,
            rmem,
            wmem,
            state,
        )
        self._tail = (self._tail + 1) & self.INDEX_MASK
        self._unconsumed_writes += 1
        occupancy = (self._tail - self._head) & self.INDEX_MASK
        if self._last_drops is not None and drops > self._last_drops:
            self._drop_rise += 1
        else:
            self._drop_rise = 0
        self._last_drops = drops
        near = (occupancy / self.CAPACITY) >= self.NEAR_RATIO
        drop_increase = self._drop_rise >= self.DROP_STREAK
        stalled = self._unconsumed_writes >= self.STALL_WRITES
        if near:
            self._latch(
                "near",
                f"ring occupancy {occupancy}/{self.CAPACITY} near capacity",
            )
        else:
            self._latched["near"] = False
        if drop_increase:
            self._latch("drops", "drop counter increased monotonically")
        else:
            self._latched["drops"] = False
        if stalled:
            self._latch(
                "stall",
                "consumer stalled; head held while the producer wrote",
            )
        else:
            self._latched["stall"] = False
        self._depths.append(float(depth))
        mean_depth = float(statistics.fmean(self._depths))
        if len(self._depths) > 1:
            depth_spread = float(statistics.pstdev(self._depths))
        else:
            depth_spread = 0.0
        slack = math.fabs(1.0 - (occupancy / self.CAPACITY))
        return {
            "topic": self.TOPIC,
            "forwarded": False,
            "occupancy": occupancy,
            "near_capacity": near,
            "drop_increase": drop_increase,
            "stalled": stalled,
            "warnings": self._warnings,
            "mean_depth": mean_depth,
            "depth_spread": depth_spread,
            "slack": slack,
            "head": self._head,
            "tail": self._tail,
        }

    def _consume_unlocked(self) -> dict[str, object]:
        if ((self._tail - self._head) & self.INDEX_MASK) == 0:
            return {"empty": True, "head": self._head, "tail": self._tail}
        slot = self._head & self.MASK
        offset = slot * self.FRAME.size
        length, depth, drops, rmem, wmem, state = self.FRAME.unpack_from(
            self._ring, offset
        )
        if length != self.FRAME.size:
            raise EngineKernelException(
                f"corrupted length field {length} != {self.FRAME.size}"
            )
        self._head = (self._head + 1) & self.INDEX_MASK
        self._unconsumed_writes = 0
        self._latched["stall"] = False
        return {
            "empty": False,
            "queue_depth": depth,
            "drops": drops,
            "rmem_alloc": rmem,
            "wmem_alloc": wmem,
            "state": state,
            "length": length,
            "head": self._head,
            "tail": self._tail,
        }

    def _coerce(self, sample: dict[str, int]) -> tuple[int, int, int, int, int]:
        if not isinstance(sample, dict):
            raise EngineKernelException("sample must be a dict")
        missing = [key for key in self._FIELDS if key not in sample]
        if missing:
            raise EngineKernelException("sample missing fields")
        values: list[int] = []
        for key in self._FIELDS:
            raw = sample[key]
            if isinstance(raw, bool) or not isinstance(raw, int):
                raise EngineKernelException(f"field {key} must be an int")
            if raw < 0 or raw > 0xFFFFFFFF:
                raise EngineKernelException(f"field {key} out of range")
            values.append(raw)
        if values[4] > 0xFFFF:
            raise EngineKernelException("state exceeds record width")
        return values[0], values[1], values[2], values[3], values[4]

    def _mask_index(self, value: int, label: str) -> int:
        if isinstance(value, bool) or not isinstance(value, int):
            raise EngineKernelException(f"{label} must be an int")
        return value & self.INDEX_MASK

    def _latch(self, key: str, message: str) -> None:
        if self._latched[key]:
            return
        self._latched[key] = True
        self._warnings += 1
        LOGGER.warning("%s", message)


def _sample(
    queue_depth: int,
    drops: int,
    rmem_alloc: int,
    wmem_alloc: int = 2048,
    state: int = 1,
) -> dict[str, int]:
    return {
        "queue_depth": queue_depth,
        "drops": drops,
        "rmem_alloc": rmem_alloc,
        "wmem_alloc": wmem_alloc,
        "state": state,
    }


async def run_scenario() -> dict[str, object]:
    engine = SocketRingInspector()
    text = engine.render_sockstat(used=128, tcp_mem=12, udp_mem=2)
    parsed = engine.parse_sockstat(text)
    if parsed["used"] != 128 or parsed["tcp_mem"] != 12:
        raise EngineKernelException("sockstat round trip failed")
    rmem = parsed["tcp_mem"] * engine.PAGE_BYTES
    inbox: asyncio.Queue[dict[str, int]] = asyncio.Queue()
    for index in range(5):
        await inbox.put(_sample(12 + index, 4, rmem))
    while not inbox.empty():
        viewed = await engine.observe(inbox.get_nowait())
        if viewed["forwarded"] is not False:
            raise EngineKernelException("ring record was forwarded")
        await engine.consume_one()
    burst = engine
    last: dict[str, object] = {}
    for index in range(880):
        last = await burst.observe(
            _sample(queue_depth=40 + (index % 50), drops=10 + index, rmem_alloc=rmem)
        )
    if not last["stalled"] or not last["drop_increase"] or not last["near_capacity"]:
        raise EngineKernelException("burst telemetry conditions were not detected")
    wrapped = SocketRingInspector()
    wrapped.prime_indices(0xFFFFFFFF, 0xFFFFFFFF)
    spun = await wrapped.observe(_sample(7, 1, rmem))
    if spun["tail"] != 0:
        raise EngineKernelException("uint32 tail did not wrap")
    read_back = await wrapped.consume_one()
    if read_back["empty"] or read_back["queue_depth"] != 7 or read_back["head"] != 0:
        raise EngineKernelException("wrapped record did not read back")
    damaged = SocketRingInspector()
    await damaged.observe(_sample(3, 0, rmem))
    damaged.overlay_length(0, 1)
    corrupt_rejected = False
    try:
        await damaged.consume_one()
    except EngineKernelException:
        corrupt_rejected = True
        LOGGER.error("corrupted length field rejected on read")
    if not corrupt_rejected:
        raise EngineKernelException("corrupted length field was accepted")
    summary = {
        "topic": engine.TOPIC,
        "forwarded": False,
        "occupancy": last["occupancy"],
        "warnings": last["warnings"],
        "near_capacity": last["near_capacity"],
        "stalled": last["stalled"],
        "drop_increase": last["drop_increase"],
        "tail_after_wrap": spun["tail"],
        "corrupt_rejected": corrupt_rejected,
    }
    LOGGER.info(
        "scenario complete topic=%s forwarded=%s occupancy=%s",
        engine.TOPIC,
        False,
        last["occupancy"],
    )
    return summary


def main() -> int:
    summary = asyncio.run(run_scenario())
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
